exclude: ^\.vscode/.*$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c   # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md,markdown']
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-ast
  - id: fix-byte-order-marker
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
    exclude: tests/data/.*
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
    exclude: '.devcontainer/.*'
  - id: pretty-format-json
    exclude: '.devcontainer/.*'
    args:
    - --indent
    - '4'
    - --autofix
    - --no-sort-keys
  - id: check-toml
- repo: https://github.com/psf/black
  rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # frozen: 26.5.1
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 7f321d375f31a2f03833bc9a548e8783f2b5c420  # frozen: 9.0.0b1
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316   # frozen: v1.10.0
  hooks:
  - id: python-no-eval
  - id: python-no-log-warn
- repo: https://github.com/asottile/pyupgrade
  rev: 75992aaa40730136014f34227e0135f63fc951b4  # frozen: v3.21.2
  hooks:
  - id: pyupgrade
    args:
    - "--py310-plus"
- repo: https://github.com/PyCQA/autoflake
  rev: 2d3853a9f31d97783fb2e181d41cd82a6babd666  # frozen: v2.3.3
  hooks:
  - id: autoflake

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: system
    types_or: [python, pyi]
  - id: ruff-check
    name: ruff check
    entry: ruff check --fix
    language: system
    types_or:
    - python
    - pyi
  - id: ruff-format
    name: ruff format
    entry: ruff format
    language: system
    types_or:
    - python
    - pyi
  - id: replace-non-ascii
    name: replace non ascii characters
    entry: python3 tools/escape_non_ascii.py
    language: python
    types: [python]
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 8d1b9cadaf854cb25bb0b0f5870e1cc66a083d6b   # frozen: 0.2.3
  hooks:
  - id: yamlfmt
    args:
    - --mapping
    - '2'
    - --sequence
    - '2'
    - --offset
    - '0'
    - --width
    - '120'
    - -e
    - -p
- repo: https://github.com/commitizen-tools/commitizen
  rev: 1afca4a81ca3e578ba142fe15a0f8a1a94b894ad  # frozen: v4.17.0
  hooks:
  - id: commitizen
- repo: https://github.com/andreoliwa/nitpick
  rev: '3ba97e5d57882cca6ef1eccaae683753c8a26630'  # frozen: v0.38.1
  hooks:
  - id: nitpick
- repo: https://github.com/ikamensh/flynt
  rev: '97be693bf18bc2f050667dd282d243e2824b81e2'    # frozen: 1.0.6
  hooks:
  - id: flynt
- repo: https://github.com/codespell-project/codespell
  rev: '57b21406f092110c18776e39b0bda50d37c945c8'  # frozen: v2.4.3
  hooks:
  - id: codespell
    exclude: data/.*
    additional_dependencies:
    - tomli ; python_version < '3.11'
- repo: https://github.com/MarcoGorelli/auto-walrus
  rev: '1743edbed52f3d61886b59d98a27164a8af29c0d'  # frozen: 0.4.1
  hooks:
  - id: auto-walrus
    additional_dependencies:
    - tomli ; python_version < '3.11'
- repo: https://github.com/JelleZijlstra/autotyping
  rev: 4dcb8d9dcb3dceedce8de4df074d18de0b7cfe3c  # frozen: 24.9.0
  hooks:
  - id: autotyping
    stages:
    - pre-commit
    args:
    - --annotate-named-param
    - conn:cloudbot.client.Client
    - --safe
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: '4380fbb73a154b5f5624794c1c78d9719ccc860f'  # frozen: v2.16.0
  hooks:
  - id: pretty-format-toml
    args:
    - --autofix
    - --no-sort
    - --trailing-commas
    - --indent
    - '4'
    - --inline-comment-spaces
    - '1'
minimum_pre_commit_version: 4.3.0
default_install_hook_types:
- pre-commit
- pre-push
- commit-msg
