name: "Push Notification"
on: [push, pull_request, create]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: irc pull request
      uses: rectalogic/notify-irc@v1
      if: github.event_name == 'pull_request'
      with:
        channel: "#gonzobot-dev"
        nickname: tnr-git
        server: irc.snoonet.org
        sasl_password: ${{ secrets.IRC_PASSWORD }}
        message: |
          ${{ github.actor }} opened PR ${{ github.event.pull_request.html_url }}
    - name: irc tag created
      uses: rectalogic/notify-irc@v1
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      with:
        channel: "#gonzobot-dev"
        nickname: tnr-git
        server: irc.snoonet.org
        sasl_password: ${{ secrets.IRC_PASSWORD }}
        message: |
          ${{ github.actor }} tagged ${{ github.repository }} ${{ github.event.ref }}
