name: Mypy type checking
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - uses: actions/cache@v3.3.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install apt deps
      run: sudo apt-get update && sudo apt-get install -qq -y libxml2-dev libxslt1-dev
    - name: Install dependencies
      run: pip install -Ur requirements-dev.txt
    - name: Test with mypy
      run: pre-commit run mypy --all
