name: Run nitpick to sync CI configs

on:
  schedule:
  - cron: '0 3 * * 1'   # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  nitpick:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803   # v6.1.0

    - name: Install nitpick
      run: pipx install nitpick

    - name: Run nitpick
      run: nitpick fix || true
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1   # v8.1.1
      with:
        commit-message: "ci(nitpick): Sync CI configs"
        title: "ci(nitpick): Sync CI configs"
        body: "Automated run of nitpick fix."
        branch: "nitpick"
        base: ${{ github.ref_name }}
        labels: "nitpick"
        reviewers: "linuxdaemon"
        assignees: "linuxdaemon"
        sign-commits: true
