name: Update .pre-commit-config.yaml

on:
  schedule:
  - cron: '0 3 * * *'   # Every day at 03:00 UTC
  workflow_dispatch:

jobs:
  update-pre-commit-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803   # v6.1.0

    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1   # v6.3.0
      with:
        python-version: '3.14'
        cache: "pip"

    - name: Install pre-commit
      run: pip install --upgrade pre-commit

    - name: Set up Git user
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Update .pre-commit-config.yaml
      run: pre-commit autoupdate --freeze

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1   # v8.1.1
      with:
        commit-message: "chore(deps): Update .pre-commit-config.yaml"
        title: "chore(deps): Update .pre-commit-config.yaml"
        body: "Automated update of .pre-commit-config.yaml via scheduled workflow."
        branch: "update/pre-commit-config-yaml"
        base: ${{ github.ref_name }}
        labels: "update"
        reviewers: "linuxdaemon"
        assignees: "linuxdaemon"
        sign-commits: true
