name: Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test:
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-ver:
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        - '3.14'
        os:
        - 'ubuntu-latest'
        - 'windows-latest'
        - 'macos-latest'
        exclude:
        - os: 'macos-latest'
          python-ver: '3.10'
        - os: 'macos-latest'
          python-ver: '3.11'

    runs-on: ${{matrix.os}}
    name: "Python ${{matrix.python-ver}} tests on ${{matrix.os}}"
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 2

    - name: Setup Python ${{matrix.python-ver}}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
      with:
        python-version: "${{matrix.python-ver}}"
        cache: "pip"
        cache-dependency-path: |
          **/*requirements*.txt

    - name: Install apt deps
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -qq -y libxml2-dev libxslt1-dev

    - name: Install dependencies
      run: |
        pip install -U pip wheel
        pip install -Ur requirements-dev.txt

    - name: Run pre-commit
      run: pre-commit run --all
      env:
        SKIP: yamlfmt

    - name: Run yamlfmt
      if: runner.os != 'Windows'
      run: pre-commit run yamlfmt --all

    - name: Test with pytest
      run: pytest --junitxml=junit.xml -o junit_family=legacy
      env:
        PYTHONDEVMODE: 1
        PYTHONPATH: .
        SQLALCHEMY_WARN_20: 1

    - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5
      with:
        name: build-${{ matrix.python-ver }}
        fail_ci_if_error: true
        use_oidc: true
        flags: unittests

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
      with:
        name: build-${{ matrix.python-ver }}
        fail_ci_if_error: true
        use_oidc: true
        flags: unittests
