name: Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test:
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-ver:
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        - '3.14'
        os:
        - 'ubuntu-latest'
        - 'windows-latest'
        - 'macos-latest'
        exclude:
        - os: 'macos-latest'
          python-ver: '3.10'
        - os: 'macos-latest'
          python-ver: '3.11'

    runs-on: ${{matrix.os}}
    name: "Python ${{matrix.python-ver}} tests on ${{matrix.os}}"
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        fetch-depth: 2

    - name: Setup Python ${{matrix.python-ver}}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "${{matrix.python-ver}}"
        cache: "pip"
        cache-dependency-path: |
          **/*requirements*.txt

    - name: Install apt deps
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -qq -y libxml2-dev libxslt1-dev

    - name: Install dependencies
      run: |
        pip install -U pip wheel
        pip install -Ur requirements-dev.txt

    - name: cache pre-commit
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{runner.os}}-${{matrix.python-ver}}
        restore-keys: |
          pre-commit-${{runner.os}}-

    - name: Run pre-commit
      run: pre-commit run --all
      env:
        SKIP: yamlfmt,nitpick

    - name: Run yamlfmt
      if: runner.os != 'Windows'
      run: pre-commit run yamlfmt --all

    - name: Test with pytest
      run: pytest --junitxml=junit.xml
      env:
        PYTHONDEVMODE: 1
        PYTHONPATH: .
        SQLALCHEMY_WARN_20: 1

    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        name: build-${{ matrix.python-ver }}
        fail_ci_if_error: true
        use_oidc: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        name: build-${{ matrix.python-ver }}
        fail_ci_if_error: true
        use_oidc: true
        report_type: test_results
